language: ruby
rvm:
  - 2.4.1

install: gem install jekyll jekyll-feed bootstrap-sass jekyll-archives jekyll-paginate
script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

deploy:
    provider: script
    script: ~/.local/bin/aws s3 sync /home/travis/build/grange85/lets-fold-scarves/_site s3://www.moley75.co.uk --region=eu-west-2 --delete
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
notifications:
    email:
        on_failure: always



# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
