title: Let's Fold Scarves
email: hazel@moley75.co.uk
description: > 
  It's what I am.
baseurl: "" 
url: "http://www.moley75.co.uk" 
twitter_username: moley75
permalink: /:year/:month/:day/:title/
favicon: favicon.ico
theme: no-style-please
theme_config:
  appearance: "light"
  back_home_text: "<-- back to home"
  date_format: "%Y-%m-%d"
  show_description: true
  post_navigation: true

goat_counter: moley75
banner_image: /images/mary-lets-fold-scarves.jpg

# Build settings
version: 4.2.0
host: 0.0.0.0
port: 4050
markdown: kramdown
plugins: [
        jekyll-feed,
        ]
        
main_categories:
   - Amber Benson
   - Books
   - Buffy the Vampire Slayer
   - Cats
   - Comics
   - Female thinking
   - Films
   - Hitchcock
   - London
   - Misc
   - Music
   - Television
   - Theatre

environment: production
future: false
exclude: 
  - vendor
  - _notes
  - Rakefile
  - .git
  - config
  - _deploy
  - _site
  - .jekyll-cache
  - "*.swp"
  - "*.swo"
  - "*.swn"

keep_files:
  - images
excerpt_separator: <!--more-->
