# Site settings
title: Let's Fold Scarves
email: hazel@moley75.co.uk
description: > # this means to ignore newlines until "baseurl:"
  It's what I am.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.moley75.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: moley75
github_username: grange85
permalink: /:year/:month/:day/:title/
jekyll-archives:
  enabled: ['month','categories']
  layouts:
    month: month-archive
    category: category-archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
pagination: 
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/page:num/'
  title: ':title - page :num'
  limit: 10
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'


# Build settings
version: 4.2.0
host: 0.0.0.0
port: 4050
markdown: kramdown
plugins: [
        jekyll-feed,
        bootstrap-sass,
        jekyll-archives,
        jekyll-paginate-v2
        ]
        
environment: production
destination: ./_deploy/
future: false
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    'Rakefile',
    'vendor',
    '.sass-cache',
    '.git',
    's3cfg-prog',
    's3cfg-prog.enc',
    'config',
    'vendor',
    'deploy.sh',
    '_deploy',
    '_cloudfront-distriution-id'
  ]
keep_files:
  - images
excerpt_separator: <!--more-->
