name: LFS
on:
  workflow_dispatch:
    inputs:
      tags:
        description: manual deploy
  push:
    branches:
      - main
  schedule:
    - cron: 37 6 * * *
jobs:
  deployment:
    runs-on: ubuntu-20.04
    environment:
      name: production
      url: https://www.moley75.co.uk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Build site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_build.yml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Sync output to S3 (full)
        if: "contains(github.event.head_commit.message, '[full]')"
        run: |
          aws s3 sync --delete --exclude '.sass-cache' _deploy s3://www-new.moley75.co.uk/
      - name: Sync output to S3 (quick)
        if: "!contains(github.event.head_commit.message, '[data]')"
        run: >
          aws s3 sync --delete --size-only --exclude '.sass-cache' _deploy s3://www-new.moley75.co.uk/
      - name: Invalidate www cloudfront
        run:
          aws cloudfront create-invalidation --no-cli-pager --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID_WWW }} --paths "/*"
      - name: Invalidate cdn cloudfront
        run:
          aws cloudfront create-invalidation --no-cli-pager --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID_CDN }} --paths "/*"
